{% set version = "2.5.2" %}
{% set name = "pycoQC" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  script: "pip install {{ name }}-{{ version }}.tar.gz --no-deps --ignore-installed -vv "
  entry_points:
    - pycoQC=pycoQC.__main__:main_pycoQC
    - Fast5_to_seq_summary=pycoQC.__main__:main_Fast5_to_seq_summary
    - Fastq_to_seq_summary=pycoQC.__main__:main_Fastq_to_seq_summary
    - Barcode_split=pycoQC.__main__:main_Barcode_split
  noarch: "python"

requirements:
  build:
    - python>=3.6
    - pip>=19.2.1
    - ripgrep>=11.0.1
  run:
    - numpy>=1.19
    - scipy>=1.5
    - pandas>=1.1
    - plotly==4.1.0
    - jinja2>=2.10
    - h5py>=3.1
    - tqdm>=4.54
    - pysam>=0.16
    - Cython>=3.0.0

test:
  imports:
    - pycoQC.pycoQC
    - pycoQC.Fast5_to_seq_summary
    - pycoQC.Fastq_to_seq_summary
    - pycoQC.Barcode_split
  commands:
    - pycoQC --help
    - Fast5_to_seq_summary --help
    - Fastq_to_seq_summary --help
    - Barcode_split --help

about:
  home: https://github.com/a-slide/pycoQC
  doc_url: https://adrienleger.com/pycoQC
  license: GPLv3
  licence_url: https://www.gnu.org/licenses/gpl-3.0.en.html
  summary: PycoQC computes metrics and generates interactive QC plots for Oxford Nanopore technologies sequencing data

extra:
  author: Adrien Leger & Tommaso Leonardi
  author_email: aleg@ebi.ac.uk
  author_url: https://adrienleger.com
